# Generated by Django 2.0 on 2017-12-22 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171222_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('type', models.CharField(choices=[('op01', 'Gato'), ('op02', 'Perro'), ('op03', 'Loro'), ('op04', 'Que se yo')], default='0p01', help_text='Pet Type', max_length=4)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Food')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='passport',
            field=models.CharField(help_text='Passport', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Owner'),
        ),
    ]
