# Generated by Django 2.0 on 2017-12-22 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171222_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
